/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Exportacao.GeradorPDF;
import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bruno
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public telaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuClientes = new javax.swing.JMenu();
        btntableCliente = new javax.swing.JMenuItem();
        btnInserirCliente = new javax.swing.JMenuItem();
        btnEditarCliente = new javax.swing.JMenuItem();
        btnDeletarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        tableQueijo = new javax.swing.JMenuItem();
        inserirQueijo = new javax.swing.JMenuItem();
        EditQueijo = new javax.swing.JMenuItem();
        delQueijo = new javax.swing.JMenuItem();
        MenuPedidos = new javax.swing.JMenu();
        tablePedido = new javax.swing.JMenuItem();
        inserirPedido = new javax.swing.JMenuItem();
        editPedido = new javax.swing.JMenuItem();
        delPedido = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Telefone", "Endereço", "Instagram", "Email", "Facebook", "Cartao de Credito"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("Tabela de Clientes");

        jButton1.setText("Novo Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar Cliente");

        jButton3.setText("Buscar Cliente");

        jButton4.setText("Remover Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Queijo.jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fabrica de Queijos");

        MenuClientes.setBorder(null);
        MenuClientes.setText("Clientes");

        btntableCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TabelaIcon.png"))); // NOI18N
        btntableCliente.setText("Tabela");
        btntableCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntableClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(btntableCliente);

        btnInserirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdicionarIcon.png"))); // NOI18N
        btnInserirCliente.setText("Inserir");
        btnInserirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(btnInserirCliente);

        btnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditarIcon.png"))); // NOI18N
        btnEditarCliente.setText("Editar");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(btnEditarCliente);

        btnDeletarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lixeira.png"))); // NOI18N
        btnDeletarCliente.setText("Deletar");
        btnDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarClienteActionPerformed(evt);
            }
        });
        MenuClientes.add(btnDeletarCliente);

        jMenuBar1.add(MenuClientes);

        jMenu3.setText("Queijos");

        tableQueijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TabelaIcon.png"))); // NOI18N
        tableQueijo.setText("Tabela");
        tableQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableQueijoActionPerformed(evt);
            }
        });
        jMenu3.add(tableQueijo);

        inserirQueijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdicionarIcon.png"))); // NOI18N
        inserirQueijo.setText("Inserir");
        inserirQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirQueijoActionPerformed(evt);
            }
        });
        jMenu3.add(inserirQueijo);

        EditQueijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditarIcon.png"))); // NOI18N
        EditQueijo.setText("Editar");
        EditQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditQueijoActionPerformed(evt);
            }
        });
        jMenu3.add(EditQueijo);

        delQueijo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lixeira.png"))); // NOI18N
        delQueijo.setText("Deletar");
        delQueijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delQueijoActionPerformed(evt);
            }
        });
        jMenu3.add(delQueijo);

        jMenuBar1.add(jMenu3);

        MenuPedidos.setText("Pedidos");

        tablePedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TabelaIcon.png"))); // NOI18N
        tablePedido.setText("Tabela");
        tablePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablePedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(tablePedido);

        inserirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdicionarIcon.png"))); // NOI18N
        inserirPedido.setText("Inserir");
        inserirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(inserirPedido);

        editPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EditarIcon.png"))); // NOI18N
        editPedido.setText("Editar");
        editPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(editPedido);

        delPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Remover Icon.png"))); // NOI18N
        delPedido.setText("Deletar");
        delPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delPedidoActionPerformed(evt);
            }
        });
        MenuPedidos.add(delPedido);

        jMenuBar1.add(MenuPedidos);

        jMenu4.setText("Exportar");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PDF.png"))); // NOI18N
        jMenuItem9.setText("Exportar PDF");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirClienteActionPerformed
        NovoCliente tela = new NovoCliente();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInserirClienteActionPerformed

    private void inserirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirPedidoActionPerformed
        NovoPedido tela = new NovoPedido();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_inserirPedidoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inserirQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirQueijoActionPerformed
        NovoQueijo tela = new NovoQueijo();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_inserirQueijoActionPerformed

    private void btntableClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntableClienteActionPerformed
        TabelaCliente table = new TabelaCliente();
        table.setVisible(true);
        table.setLocationRelativeTo(null);
    }//GEN-LAST:event_btntableClienteActionPerformed

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        EditarCliente tela = new EditarCliente();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarClienteActionPerformed
        DeletarCliente tela = new DeletarCliente();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnDeletarClienteActionPerformed

    private void tableQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableQueijoActionPerformed
        TabelaQueijo table = new TabelaQueijo();
        table.setVisible(true);
        table.setLocationRelativeTo(null);
    }//GEN-LAST:event_tableQueijoActionPerformed

    private void EditQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditQueijoActionPerformed
        EditarQueijo tela = new EditarQueijo();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_EditQueijoActionPerformed

    private void delQueijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delQueijoActionPerformed
        DeletarQueijo tela = new DeletarQueijo();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_delQueijoActionPerformed

    private void tablePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablePedidoActionPerformed
        TabelaPedidos table = new TabelaPedidos();
        table.setVisible(true);
        table.setLocationRelativeTo(null);
    }//GEN-LAST:event_tablePedidoActionPerformed

    private void editPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPedidoActionPerformed
        EditarPedido tela = new EditarPedido();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_editPedidoActionPerformed

    private void delPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delPedidoActionPerformed
        DeletarPedido tela = new DeletarPedido();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_delPedidoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        GeradorPDF pdf = new GeradorPDF();
        try {
            pdf.gerarPDF();
        } catch (DocumentException | FileNotFoundException ex) {
            Logger.getLogger(telaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EditQueijo;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenu MenuPedidos;
    private javax.swing.JMenuItem btnDeletarCliente;
    private javax.swing.JMenuItem btnEditarCliente;
    private javax.swing.JMenuItem btnInserirCliente;
    private javax.swing.JMenuItem btntableCliente;
    private javax.swing.JMenuItem delPedido;
    private javax.swing.JMenuItem delQueijo;
    private javax.swing.JMenuItem editPedido;
    private javax.swing.JMenuItem inserirPedido;
    private javax.swing.JMenuItem inserirQueijo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem tablePedido;
    private javax.swing.JMenuItem tableQueijo;
    // End of variables declaration//GEN-END:variables
}
